[ids]
*

[caps_mods]
a=leftcontrol
d=leftalt
f=leftmeta
h=left
j=down
k=up
l=right
s=leftshift
space=layer(symbols)
/=capslock

[halfqwerty_mode]
`=backspace
capslock=enter
q+r=toggle(halfqwerty_mode)
space=overload(mirror, space)

[main]
capslock=overload(caps_mods, esc)
q+r=toggle(halfqwerty_mode)
rightalt=layer(symbols)

[mirror]
,=x
.=z
;=a
`=backspace
a=;
c=m
d=k
e=i
f=j
g=h
h=g
i=e
j=f
k=d
l=s
m=c
n=v
o=w
p=q
q=p
r=u
s=l
t=y
u=r
v=n
w=o
x=,
y=t
z=.

[symbols]
capslock=capslock
,=}
.=\
/=|
;=)
a=!
apostrophe=_
b=[
c=-
d=#
e=3
f=$
g=%
h=^
i=8
j=&
k=*
l=(
leftbrace=-
m={
n=]
o=9
p=0
q=1
r=4
rightbrace==
s=@
t=5
u=7
v==
w=2
x=~
y=6
z=`
