[ids]

*

[main]

capslock = overload(caps_mods, esc)
rightalt = layer(symbols)
q+r = toggle(halfqwerty_mode)

[caps_mods]

a = leftcontrol
s = leftshift
d = leftalt
f = leftmeta
space = layer(symbols)
h = left
j = down
k = up
l = right

[symbols]

capslock = capslock
a = !
s = @
d = #
f = $
g = %
h = ^
j = &
k = *
l = (
; = )
apostrophe = _
q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0
leftbrace = -
rightbrace = =
z = `
x = ~
c = -
v = =
b = [
n = ]
m = {
, = }
. = \
/ = |

[halfqwerty_mode]

q+r = toggle(halfqwerty_mode)
space = overload(mirror, space)
capslock = enter
` = backspace

[mirror]

` = backspace
q = p
w = o
e = i
r = u
t = y
a = ;
s = l
d = k
f = j
g = h
z = .
x = ,
c = m
v = n
p = q
o = w
i = e
u = r
y = t
; = a
l = s
k = d
j = f
h = g
. = z
, = x
m = c
n = v
